### ISSUE TITLE
Improve markup handling for empty datasets

### ISSUE THREAD

**Issue by brendanfalkowski** [twitter/typeahead.js#1070]
Ran into an issue while testing with multiple datasets, ex: (keywords, brands, products). The menu renders like this when typeahead is inactive:

``` html
<span class="tt-dropdown-menu">
    <div class="tt-dataset-keywords"></div>
    <div class="tt-dataset-brands"></div>
    <div class="tt-dataset-products"></div>
</span>
```

Each dataset has a header template:

``` javascript
{header: '<h2 class="tt-header">Keywords</div>'}
```

And the following CSS adds some padding/borders (with exception for the first dataset):

``` css
.tt-header {
    margin: 8px 0 0;
    padding: 15px 15px 5px;
    border-top: 1px solid #D0D0D0;
}

[class^='tt-dataset']:first-child .tt-header {
    margin-top:0;
    padding-top:0;
    border-top:0;
}
```

When the query matches all datasets it looks nice:

![screen shot 2014-12-10 at 11 58 22 pm](https://cloud.githubusercontent.com/assets/214924/5389320/834fa0ee-80c8-11e4-935e-e77a5c0f8b27.png)

But when some datasets have no matches it gets messy:

![screen shot 2014-12-11 at 12 00 11 am](https://cloud.githubusercontent.com/assets/214924/5389329/b6e9dcf8-80c8-11e4-94b7-ee92595678ce.png)

This happens because the `tt-dataset-xyz` elements stay in the markup regardless of whether content is rendering in them. No template is rendered for "keywords" but its wrapper `tt-dataset-keywords` exists and is the `first-child`. Since there's no way to write a CSS selector that tests if an older sibling had children, the markup needs to be modified.

The `tt-dataset-xyz` should be removed from `tt-dropdown-menu` when it is empty. This would need to be an option for backwards compatibility where an empty template is used. Something like `renderIfEmpty` in the dataset definition:

``` javascript
{
    name: 'keywords',
    displayKey: 'value',
    source: keywords.ttAdapter(),
    templates: {
        header: '<h2 class="tt-header">Keywords</div>'
    },
    renderIfEmpty: false
}
```
