### ISSUE TITLE
Mistake in typeahead scrollable example

### ISSUE THREAD

**Issue by dtolstyi** [twitter/typeahead.js#1743]
An example shows that to enable scrolling for your typeahead instance you need to add next CSS:
```css
#scrollable-dropdown-menu .tt-dropdown-menu {
  max-height: 150px;
  overflow-y: auto;
}
```
But `.tt-dropdown-menu` class is not present in typeahead constructed HTML.
Instead, missing class should be replaced with `.tt-menu`:
```css
#scrollable-dropdown-menu .tt-menu {
  max-height: 150px;
  overflow-y: auto;
}
```
